---
# tasks file for install_postgres
  - name: disable firewalld service
    service:
      name: firewalld
      state: stopped
      enabled: false

  # Отключаем SElinux
  - name: Disable SELinux
    selinux:
      state: disabled

  # Отключаем SElinux после перезагрузки
  - name: Ensure SELinux is set to disable mode
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled

  - name: 'Устанавливаем репозиторий postgres'
    shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    ignore_errors: yes

  - name: 'Устанавливаем пакеты'
    yum: 
      name: "{{ item }}"
      state: latest
    with_items: 
      - zabbix-server-pgsql
      - zabbix-agent
      - centos-release-scl
      - python36-pexpect
      - python-pip
      - python3-psycopg2
      - python-psycopg2
  - name: 'активируем zabbix-frontend'
    lineinfile:
      path: /etc/yum.repos.d/zabbix.repo
      regexp: '^enabled='
      insertafter: '^baseurl=http://repo.zabbix.com/zabbix/5.0/rhel/7/$basearch/frontend'
      line: 'enabled=1'
  - name: 'Устанавливаем frontend zabbix'
    yum: 
      name: "{{ item }}"
      state: latest
    with_items: 
      - zabbix-web-pgsql-scl
      - zabbix-apache-conf-scl

  - name: 'Устанавливаем репозиторий postgres'
    shell: sudo yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x$
    ignore_errors: yes

  - name: 'Устанавливаем postgres и zabbix agent'
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - postgresql14-server
      - postgresql14

  - name: 'Инициализируем postgres'
    shell: /usr/pgsql-14/bin/postgresql-14-setup initdb
    ignore_errors: yes

  - name: enable and start service
    systemd:
      name: postgresql-14
      state: started

  - name: Install pexpect
    pip:
      name: pexpect

 #Остановливаем postgresql-14 на хосте db2
  - name: stop postgresql-server on db2
    service:
      name: postgresql-14
      state: stopped
 #Копиуем конфигурационный файл postgresql.conf
  - name: copy postgresql.conf
    template:
      src: postgresql.conf.j2
      dest: /var/lib/pgsql/14/data/postgresql.conf
      owner: postgres
      group: postgres
      mode: '0600'

 #Копиуем конфигурационный файл pg_hba.conf
  - name: copy pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest: /var/lib/pgsql/14/data/pg_hba.conf
      owner: postgres
      group: postgres
      mode: '0600'

  #Перезапускаем службу  postgresql-14
  - name: restart postgresql-server on db1
    service:
      name: postgresql-14
      state: restarted


  - name: Create zabbix user
    become_user: postgres
    postgresql_user:
      name: zabbix
      password: '{{ pg_zabbix_password }}'
    ignore_errors: true

  - name: 'Создаем базу zabbix'
    become_user: postgres
    postgresql_db:
      name: zabbix
      encoding: UTF-8
      template: template0
  
  - name: 'Импортируем данные для zabbix в таблицу'
    shell: zcat /usr/share/doc/zabbix-server-pgsql/create.sql.gz | sudo -u zabbix psql zabbix

  - name: copy pg_hba.conf
    template:
      src: zabbix_server.conf.j2
      dest: /etc/zabbix/zabbix_server.conf
      owner: root
      group: zabbix
      mode: '0600'

  - name: запуск службы заббикс
    service:
      name: zabbix-server
      state: started
      enabled: yes

